// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonflow/gojudge (interfaces: Language)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLanguage is a mock of Language interface.
type MockLanguage struct {
	ctrl     *gomock.Controller
	recorder *MockLanguageMockRecorder
}

// MockLanguageMockRecorder is the mock recorder for MockLanguage.
type MockLanguageMockRecorder struct {
	mock *MockLanguage
}

// NewMockLanguage creates a new mock instance.
func NewMockLanguage(ctrl *gomock.Controller) *MockLanguage {
	mock := &MockLanguage{ctrl: ctrl}
	mock.recorder = &MockLanguageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLanguage) EXPECT() *MockLanguageMockRecorder {
	return m.recorder
}

// GetCompileCommand mocks base method.
func (m *MockLanguage) GetCompileCommand() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompileCommand")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCompileCommand indicates an expected call of GetCompileCommand.
func (mr *MockLanguageMockRecorder) GetCompileCommand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompileCommand", reflect.TypeOf((*MockLanguage)(nil).GetCompileCommand))
}

// GetExtension mocks base method.
func (m *MockLanguage) GetExtension() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExtension")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetExtension indicates an expected call of GetExtension.
func (mr *MockLanguageMockRecorder) GetExtension() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExtension", reflect.TypeOf((*MockLanguage)(nil).GetExtension))
}

// GetName mocks base method.
func (m *MockLanguage) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockLanguageMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockLanguage)(nil).GetName))
}

// GetRunCommand mocks base method.
func (m *MockLanguage) GetRunCommand() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRunCommand")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRunCommand indicates an expected call of GetRunCommand.
func (mr *MockLanguageMockRecorder) GetRunCommand() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRunCommand", reflect.TypeOf((*MockLanguage)(nil).GetRunCommand))
}

// GetSanitizeFunction mocks base method.
func (m *MockLanguage) GetSanitizeFunction() func(string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSanitizeFunction")
	ret0, _ := ret[0].(func(string) string)
	return ret0
}

// GetSanitizeFunction indicates an expected call of GetSanitizeFunction.
func (mr *MockLanguageMockRecorder) GetSanitizeFunction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSanitizeFunction", reflect.TypeOf((*MockLanguage)(nil).GetSanitizeFunction))
}

// IsCompiled mocks base method.
func (m *MockLanguage) IsCompiled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCompiled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCompiled indicates an expected call of IsCompiled.
func (mr *MockLanguageMockRecorder) IsCompiled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCompiled", reflect.TypeOf((*MockLanguage)(nil).IsCompiled))
}
