// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/canonflow/gojudge (interfaces: Judge)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gojudge "github.com/canonflow/gojudge"
	gomock "github.com/golang/mock/gomock"
)

// MockJudge is a mock of Judge interface.
type MockJudge struct {
	ctrl     *gomock.Controller
	recorder *MockJudgeMockRecorder
}

// MockJudgeMockRecorder is the mock recorder for MockJudge.
type MockJudgeMockRecorder struct {
	mock *MockJudge
}

// NewMockJudge creates a new mock instance.
func NewMockJudge(ctrl *gomock.Controller) *MockJudge {
	mock := &MockJudge{ctrl: ctrl}
	mock.recorder = &MockJudgeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJudge) EXPECT() *MockJudgeMockRecorder {
	return m.recorder
}

// Compile mocks base method.
func (m *MockJudge) Compile(arg0 context.Context, arg1 gojudge.Language, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compile indicates an expected call of Compile.
func (mr *MockJudgeMockRecorder) Compile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockJudge)(nil).Compile), arg0, arg1)
}

// GetLanguages mocks base method.
func (m *MockJudge) GetLanguages() map[string]gojudge.Language {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguages")
	ret0, _ := ret[0].(map[string]gojudge.Language)
	return ret0
}

// GetLanguages indicates an expected call of GetLanguages.
func (mr *MockJudgeMockRecorder) GetLanguages() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguages", reflect.TypeOf((*MockJudge)(nil).GetLanguages))
}

// Judge mocks base method.
func (m *MockJudge) Judge(arg0 context.Context, arg1 gojudge.Language, arg2, arg3 int) gojudge.JudgeResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Judge", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(gojudge.JudgeResult)
	return ret0
}

// Judge indicates an expected call of Judge.
func (mr *MockJudgeMockRecorder) Judge(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Judge", reflect.TypeOf((*MockJudge)(nil).Judge), arg0, arg1, arg2, arg3)
}

// RegisterNewLanguage mocks base method.
func (m *MockJudge) RegisterNewLanguage(arg0 gojudge.Language) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterNewLanguage", arg0)
}

// RegisterNewLanguage indicates an expected call of RegisterNewLanguage.
func (mr *MockJudgeMockRecorder) RegisterNewLanguage(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterNewLanguage", reflect.TypeOf((*MockJudge)(nil).RegisterNewLanguage), arg0)
}
